[config]
fallback_color = "#00aeff"

[templates.hyprpaper]
input_path = "./templates/hyprpaper-config.conf"
output_path = "~/.config/hypr/hyprpaper.conf"
post_hook = "systemctl --user restart hyprpaper.service"

[templates.kitty]
input_path = "./templates/kitty-colors.conf"
output_path = "~/.config/kitty/themes/material-theme.conf"
post_hook = "kitty +kitten themes --reload-in=all material-theme"

[templates.mako]
input_path = "./templates/mako-colors"
output_path = "~/.config/mako/colors"
post_hook = "makoctl reload"

[templates.niri]
input_path = "./templates/niri-colors.kdl"
output_path = "~/.config/niri/colors.kdl"

[templates.qt5ct]
input_path = "./templates/qtct-colors.conf"
output_path = "~/.config/qt5ct/colors/material.conf"

[templates.qt6ct]
input_path = "./templates/qtct-colors.conf"
output_path = "~/.config/qt6ct/colors/material.conf"

[templates.waywall]
input_path = "./templates/waywall-colors.lua"
output_path = "~/.config/waywall/colors.lua"

[templates.vesktop]
input_path = "./templates/discord-colors.css"
output_path = "~/.config/vesktop/themes/material.css"

[templates.zsh]
input_path = "./templates/zsh-colors.zsh"
output_path = "~/.config/zsh/10-colors.zsh"
