[config]
fallback_color = "#00aeff"

[templates.gtk3]
input_path = "./templates/gtk-colors.css"
output_path = "~/.config/gtk-3.0/colors.css"
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = "./templates/gtk-colors.css"
output_path = "~/.config/gtk-4.0/colors.css"

[templates.hypr]
input_path = "./templates/hypr-colors.conf"
output_path = "~/.config/hypr/colors.conf"
post_hook = "hyprctl reload"

[templates.hyprpaper]
input_path = "./templates/hyprpaper-config.conf"
output_path = "~/.config/hypr/hyprpaper.conf"
post_hook = "systemctl --user restart hyprpaper.service"

[templates.kitty]
input_path = "./templates/kitty-colors.conf"
output_path = "~/.config/kitty/themes/material-theme.conf"
post_hook = "kitty +kitten themes --reload-in=all material-theme"

[templates.mako]
input_path = "./templates/mako-colors"
output_path = "~/.config/mako/colors"
post_hook = "makoctl reload"

[templates.niri]
input_path = "./templates/niri-colors.kdl"
output_path = "~/.config/niri/colors.kdl"

[templates.qt5ct]
input_path = "./templates/qtct-colors.conf"
output_path = "~/.config/qt5ct/colors/material.conf"

[templates.qt6ct]
input_path = "./templates/qtct-colors.conf"
output_path = "~/.config/qt6ct/colors/material.conf"

[templates.quickshell-default]
input_path = "./templates/quickshell-colors.qml"
output_path = "~/.config/quickshell/default/common/Colors.qml"

[templates.rofi]
input_path = "./templates/rofi-colors.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.waywall]
input_path = "./templates/waywall-colors.lua"
output_path = "~/.config/waywall/colors.lua"

[templates.vesktop]
input_path = "./templates/discord-colors.css"
output_path = "~/.config/vesktop/themes/material.css"

[templates.zsh]
input_path = "./templates/zsh-colors.zsh"
output_path = "~/.config/zsh/10-colors.zsh"
